### ISSUE TITLE
BetterMediaPlayer dosen't work

### ISSUE THREAD

**Issue by TwinFox20** [jaspwr/BDPlugins#4]
I downloaded your plugin and it doesn't work. I copied raw code from github and it doesn't work either.
Without plugins:
![image](https://user-images.githubusercontent.com/57001572/232233885-dc75eee2-cfa5-412f-863a-7565c4b988c9.png)

Stable 189617 (5a59d26)
Host 1.0.9012 (30921)
Windows 10 64-Bit (10.0.19044)

My plugins:
BDFDB v3.2.6 
BetterAudioPlayer v1.0.2 
BetterChatNames v1.4.7
BetterRoleColors v0.9.1
DiscordFreeEmojis v1.7
FavoriteMedia v1.7.3
ImageUtilities v5.2.4
PluginRepo v2.5.0
SpotifyControls v1.3.4
ThemeRepo v2.5.0
Translator v2.5.5
ZeresPluginLibrary v2.0.15

My themes:
AMOLED-Cord v1.1.1

With plugins and themes:
![image](https://user-images.githubusercontent.com/57001572/232234270-e765f394-cafd-4949-a9b3-b6668c993f43.png)
My BetterMediaPlayer config:

    "currentVersionInfo": {
        "version": "1.0.2",
        "hasShownChangelog": true
    },
    "settings": {
        "showSpectrograph": true,
        "showOscilloscope": true,
        "inheritColors": true,
        "manualColorSettings": {
            "oscilloscopeColorCustom": "#FFFFFF",
            "spectrographColorCustom": "#738ADB"
        },
        "spectrographSegments": 110,
        "bypassFileSizeLimit": false
    }

**Comment by jaspwr** [comment]
Thank you for reporting. I can't seem to replicate this would you mind checking the console for any errors?

**Comment by TwinFox20** [comment]
![image](https://user-images.githubusercontent.com/57001572/233025152-0ed99bd2-6a5b-4d45-ac2c-e6f2e6971210.png)
This is all that the console output for your plugin
